### ISSUE TITLE
Local Path Mapping Not Working

### ISSUE THREAD

**Issue by stakeout55** [hjhart/seedboxio-docker-downloader#7]
Hey! Hope all is well. When I go to map the final destination for my movies and such, they always get dumped to "Storage->radarr" or "sonarr" -- thoughts? not the paths that I set in .env ... Thanks

**Comment by hjhart** [comment]
Can you attach a screen shot?

**Comment by stakeout55** [comment]
Yes I can. This is my path layout for .env

```
RSLSYNC_SECRET=(redacted)
RSLSYNC_SIZE=5000
PGID=1000
PUID=1000
TZ=America/New_York
MOVIE_DIR=/media/8TB/media/movies
TV_SHOW_DIR=/media/8TB/media/tv
STORAGE_DIR=/media/8TB/media/storage
```

Note that the **storage** directory is where auto-generated "radarr" and "sonarr" folders appeared and will download their respective files to.
![locations](https://user-images.githubusercontent.com/48146384/100524108-4e5b1180-3183-11eb-8a21-2db34e1e8e7a.png)

What I had wanted to happen, is for radarr to dump its files into the `/media/8TB/media/movies` directory and for sonarr to do the same with the `/media/8TB/media/tv` directory
![where I want them to go](https://user-images.githubusercontent.com/48146384/100524116-60d54b00-3183-11eb-8abd-a7f1df1e8821.png)

On either radarr or sonarr config, I found where Id map the local path as such:
![radarr map](https://user-images.githubusercontent.com/48146384/100524122-777ba200-3183-11eb-8852-498672bb49a0.png)

yet when I go to select new locations, such as `/media/8TB/media/movies` for radarr there are no subfolders like seen here
![no data](https://user-images.githubusercontent.com/48146384/100524134-937f4380-3183-11eb-9649-b9d5ee05ad36.png)

This is the over-arching file structure yet none of them have subfolers excpet for `downloads` which then has only one directory, the radarrr (or sonarr if under sonarr) directory that is where radarr (or sonarr) currently displays these files going to (seen two images above)
![onlyone that has another dir is downloads](https://user-images.githubusercontent.com/48146384/100524140-9c701500-3183-11eb-87ea-acd0d78898bc.png)

Also to note, if I download any file NOT through radarr or sonarr, it will download with resilio to the 'storage' directory (which is fine, again, I just don't know where to configure that if I wanted to change that is all which i'm sure partly links to my radarr / sonarr issue lol

I'm sure I'm doing something wrong... I just can't figure out what! Thank you so much for your time!

**Comment by hjhart** [comment]
Are you mounting the volumes in your `docker-compose.yml` file?

Example from mine:
```
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ./radarr/config/:/config
      - ${MOVIE_DIR}:/movies
      - ${STORAGE_DIR}/radarr:/downloads/radarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config/:/config
      - ${TV_SHOW_DIR}:/tv
      - ${STORAGE_DIR}/sonarr:/downloads/sonarr
```


Note specifically the non-config related volumes attached.

**Comment by stakeout55** [comment]
For example under radarr, is that you mean? Sorry, I'm having a tough time with this. I appreciate your help very much.

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - 7878:7878
    volumes:
      - ./radarr/config/:/config
      - ${MOVIE_DIR}:**/media/8TB/media/movies**
      - ${STORAGE_DIR}/radarr:/downloads/radarr
    env_file:
      - .env

**Comment by hjhart** [comment]
Okay, you've got it backwards.

Update your `.env` file so that you have this:

```
MOVIE_DIR=/media/8TB/media/movies
TV_SHOW_DIR=/media/8TB/media/tv
STORAGE_DIR=/media/8TB/media/storage
```

And then your docker-compose.yml file will look something like this: (most important key is the volume key).

```
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ./radarr/config/:/config
      - ${MOVIE_DIR}:/movies
      - ${STORAGE_DIR}/radarr:/downloads/radarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config/:/config
      - ${TV_SHOW_DIR}:/tv
      - ${STORAGE_DIR}/sonarr:/downloads/sonarr
```

That will allow radarr and sonarr to see downloads come in, synced from rsync, into your ${STORAGE_DIR} and move it into the MOVIE_DIR and the TV_SHOW_DIR.
